# Generated by Django 5.2.2 on 2026-06-11 10:06

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage taken from each escrow order (e.g. 5.00 = 5%)', max_digits=5)),
                ('premium_monthly_price', models.DecimalField(decimal_places=2, default=2000.0, help_text='Monthly premium subscription price in NGN', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('watermark_enabled', models.BooleanField(default=True)),
                ('country_code', models.CharField(default='+234', max_length=10)),
                ('currency_code', models.CharField(default='NGN', max_length=10)),
                ('currency_symbol', models.CharField(default='₦', max_length=10)),
                ('store_mode', models.BooleanField(default=False)),
                ('store_mode_enabled_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('electronics', 'Electronics & Gadgets'), ('food', 'Food & Beverages'), ('home', 'Home & Garden'), ('sports', 'Sports & Fitness'), ('health', 'Health & Wellness'), ('other', 'Other')], default='other', max_length=100, null=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_page_views', models.IntegerField(default=0)),
                ('weekly_page_views', models.IntegerField(default=0)),
                ('weekly_whatsapp_clicks', models.IntegerField(default=0)),
                ('last_analytics_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verify_token', models.CharField(blank=True, max_length=64, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=30)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_country', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid — Awaiting Shipment'), ('shipped', 'Shipped'), ('RECEIVED', 'Received — Awaiting 24h Payout'), ('delivered', 'Delivered'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('FAILED_PAYOUT', 'Payout Failed — Retrying Tomorrow'), ('completed', 'Completed — Paid Out')], default='pending', max_length=20)),
                ('flutterwave_tx_id', models.CharField(blank=True, max_length=200)),
                ('flutterwave_tx_ref', models.CharField(blank=True, max_length=200, unique=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_info', models.CharField(blank=True, max_length=500)),
                ('courier_name', models.CharField(blank=True, max_length=200)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('escrow', 'Escrow'), ('direct', 'Direct')], default='escrow', max_length=10)),
                ('delivery_required', models.BooleanField(default=True)),
                ('payout_triggered', models.BooleanField(default=False)),
                ('payout_at', models.DateTimeField(blank=True, null=True)),
                ('flutterwave_transfer_id', models.CharField(blank=True, max_length=200)),
                ('refund_reference', models.CharField(blank=True, max_length=200)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by', models.CharField(default='buyer', max_length=20)),
                ('reason', models.CharField(choices=[('not_received', 'Item not received'), ('wrong_item', 'Wrong item sent'), ('damaged', 'Item arrived damaged'), ('not_as_described', 'Not as described'), ('other', 'Other')], max_length=50)),
                ('buyer_message', models.TextField()),
                ('buyer_evidence', models.URLField(blank=True)),
                ('vendor_reply', models.TextField(blank=True)),
                ('vendor_evidence', models.URLField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('vendor_replied', 'Vendor Replied'), ('under_review', 'Under Admin Review'), ('resolved_buyer', 'Resolved — Refund to Buyer'), ('resolved_vendor', 'Resolved — Paid to Vendor'), ('closed', 'Closed')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='sellers.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=500)),
                ('product_image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sellers.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='sellers.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_code', models.CharField(blank=True, max_length=100)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
