# Generated by Django 5.2.2 on 2026-06-12 08:21

import sellers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seller',
            managers=[
                ('objects', sellers.models.SellerManager()),
            ],
        ),
    ]
