# Generated by Django 5.2.2 on 2026-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='watermark_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
