# Generated by Django 5.2.2 on 2026-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('electronics', 'Electronics & Gadgets'), ('food', 'Food & Beverages'), ('home', 'Home & Garden'), ('sports', 'Sports & Fitness'), ('health', 'Health & Wellness'), ('other', 'Other')], default='other', max_length=100, null=True),
        ),
    ]
