# Generated by Django 5.2.2 on 2026-03-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_watermark_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='country_code',
            field=models.CharField(default='+234', max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='currency_code',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='currency_symbol',
            field=models.CharField(default='₦', max_length=10),
        ),
    ]
