# Generated by Django 5.2.2 on 2026-06-13 07:40

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The commission % actually applied to this order (for auditing).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='monthly_volume_processed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order subtotal processed this billing month.', max_digits=14),
        ),
        migrations.AddField(
            model_name='seller',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], default='starter', help_text='Determines commission rate and monthly volume cap.', max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='tier_reset_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Last date monthly_volume_processed was reset.'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='premium_monthly_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Legacy premium subscription price in NGN (kept for backward compatibility).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='transaction_fee_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Default/fallback platform fee percentage (used when seller has no tier override).', max_digits=5),
        ),
    ]
