# Generated by Django 5.2.2 on 2026-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_order_commission_rate_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
    ]
