# Generated by Django 5.2.2 on 2026-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_seller_store_mode_seller_store_mode_enabled_at_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('escrow', 'Escrow'), ('direct', 'Direct')], default='escrow', max_length=10),
        ),
    ]
