# Generated by Django 5.2.2 on 2026-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_order_dispute_reason_order_is_disputed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this seller made any request to the platform.', null=True),
        ),
    ]
