# Generated by Django 5.2.2 on 2026-05-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_order_delivery_required_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage taken from each escrow order (e.g. 5.00 = 5%)', max_digits=5)),
                ('premium_monthly_price', models.DecimalField(decimal_places=2, default=2000.0, help_text='Monthly premium subscription price in NGN', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
