# Generated by Django 5.2.2 on 2026-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_seller_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='last_reengagement_sent',
            field=models.DateTimeField(blank=True, help_text='Last time a re-engagement email was sent to this seller.', null=True),
        ),
    ]
