# Generated by Django 5.2.2 on 2026-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankaccount',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
