# Generated by Django 5.2.2 on 2026-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_vendorbankaccount_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
