# Generated by Django 5.2.2 on 2026-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_order_refund_initiated_at_order_refund_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_verify_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
