# Generated by Django 5.2.2 on 2026-04-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
